const fs = require('fs-extra')
if (fs.existsSync('.env')) require('dotenv').config({ path: __dirname+'/.env' })


//═══════[Required Variables]════════\\
global.audio= "" ;  
global.video= "" ;
global.port =process.env.PORT
global.appUrl=process.env.APP_URL || ""                       // put your app url here,
global.email ="samsamsun789@gmail.com"
global.location="Lahore,Pakistan."
global.mongodb= process.env.MONGODB_URI || ""
global.allowJids= process.env.ALLOW_JID || "null" 
global.blockJids= process.env.BLOCK_JID || "120363023983262391@g.us"
global.DATABASE_URI = process.env.DATABASE_URL || ""

global.timezone= process.env.TZ || process.env.TIME_ZONE || "Asia/Karachi";
global.github=process.env.GITHUB|| "https://github.com/SuhailTechInfo/Suhail-Md";
global.gurl  =process.env.GURL  || "https://whatsapp.com/channel/0029Va9thusJP20yWxQ6N643";
global.website=process.env.GURL || "https://whatsapp.com/channel/0029Va9thusJP20yWxQ6N643" ; 
global.THUMB_IMAGE = process.env.THUMB_IMAGE || process.env.IMAGE || "https://telegra.ph/file/d5b1c3544fedc23e11a06.jpg" ; // SET LOGO FOR IMAGE 



global.devs = "923184474176" // Developer Contact
global.sudo = process.env.SUDO ? process.env.SUDO.replace(/[\s+]/g, '') : "null";
global.owner= process.env.OWNER_NUMBER ? process.env.OWNER_NUMBER.replace(/[\s+]/g, '') : "2349067082699";




//========================= [ BOT SETTINGS ] =========================\\
global.style = process.env.STYLE   || '5',  // put '1' to "5" here to check bot styles
global.flush = process.env.FLUSH   || "false"; // Make it "true" if bot not responed
global.gdbye = process.env.GOODBYE || "false"; 
global.wlcm  = process.env.WELCOME || "true";  // Make it "false" for disable WELCOME 

global.warncount = process.env.WARN_COUNT || 3,
global.disablepm = process.env.DISABLE_PM || "false",
global.MsgsInLog = process.env.MSGS_IN_LOG|| "false", // "true"  to see messages , "log" to open logs , "false" to hide logs messages
global.userImages= process.env.USER_IMAGES|| "text",
global.waPresence= process.env.WAPRESENCE ||  "set according to your need" ; // 'unavailable' | 'available' | 'composing' | 'recording' | 'paused'


//========================= [ AUTO READ MSGS & CMDS ] =========================\\
global.readcmds = process.env.READ_COMMAND || "false"
global.readmessage = process.env.READ_MESSAGE || "false"
global.readmessagefrom = process.env.READ_MESSAGE_FROM || "923184474176,923xxxxxxxx";


//========================= [ AUTO SAVE & READ STATUS ] =========================\\
global.read_status = process.env.AUTO_READ_STATUS || "false"
global.save_status = process.env.AUTO_SAVE_STATUS || "false"
global.save_status_from =  process.env.SAVE_STATUS_FROM  || "null,923xxxxxxxx";
global.read_status_from =  process.env.READ_STATUS_FROM  ||  "2349067082699";

global.api_smd = "https://api-smd-1.vercel.app"
global.scan = "https://suhail-md-vtsf.onrender.com/";

module.exports = {

  menu: process.env.MENU || "", /**  Available @MENU @Schemes 1: Aztec_Md, 2: A17_Md, 3: Suhail-Md Default ---------- If Not Choose then it Randomely Pic One Of Them Each time **/

  HANDLERS: process.env.PREFIX  || ".",
  BRANCH  : process.env.BRANCH  || "main",
  VERSION : process.env.VERSION || "V.1.2.8",
  caption : process.env.CAPTION || "©sᴜʜᴀɪʟ²²¹-ᴍᴅ" , // ```『 ᴘᴏᴡᴇʀᴇᴅ ʙʏ sᴜʜᴀɪʟ²²¹-ᴍᴅ 』```", //*『sᴜʙsᴄʀɪʙᴇ • sᴜʜᴀɪʟ ᴛᴇᴄʜ』*\n youtube.com/@suhailtechinfo0"),
 
  author : process.env.PACK_AUTHER|| "Suhail-MD",
  packname: process.env.PACK_NAME || "♥️",
  botname : process.env.BOT_NAME  || "sᴜʜᴀɪʟ-ᴍᴅ",
  ownername:process.env.OWNER_NAME|| "It'x Suhail"

  sessionName:process.env.SESSION_ID || "SUHAIL_13_46_09_02_ewogICJjcmVkcy5qc29uIjogIntcbiAgXCJub2lzZUtleVwiOiB7XG4gICAgXCJwcml2YXRlXCI6IHtcbiAgICAgIFwidHlwZVwiOiBcIkJ1ZmZlclwiLFxuICAgICAgXCJkYXRhXCI6IFtcbiAgICAgICAgMjE2LFxuICAgICAgICAyMjYsXG4gICAgICAgIDc5LFxuICAgICAgICAxNTYsXG4gICAgICAgIDEwMSxcbiAgICAgICAgMTA1LFxuICAgICAgICAxOTUsXG4gICAgICAgIDEzMixcbiAgICAgICAgMjEzLFxuICAgICAgICAxOTYsXG4gICAgICAgIDEwNCxcbiAgICAgICAgMjA5LFxuICAgICAgICA0NyxcbiAgICAgICAgMTIyLFxuICAgICAgICA1MixcbiAgICAgICAgMjI5LFxuICAgICAgICA1NixcbiAgICAgICAgNzAsXG4gICAgICAgIDExMSxcbiAgICAgICAgOTIsXG4gICAgICAgIDEzMixcbiAgICAgICAgMTgwLFxuICAgICAgICA5MyxcbiAgICAgICAgNzcsXG4gICAgICAgIDY5LFxuICAgICAgICAzOSxcbiAgICAgICAgMjIxLFxuICAgICAgICAyMTMsXG4gICAgICAgIDE3MCxcbiAgICAgICAgNzgsXG4gICAgICAgIDE1MCxcbiAgICAgICAgNjVcbiAgICAgIF1cbiAgICB9LFxuICAgIFwicHVibGljXCI6IHtcbiAgICAgIFwidHlwZVwiOiBcIkJ1ZmZlclwiLFxuICAgICAgXCJkYXRhXCI6IFtcbiAgICAgICAgMTA1LFxuICAgICAgICAyMjAsXG4gICAgICAgIDIyOCxcbiAgICAgICAgMjMzLFxuICAgICAgICA4NSxcbiAgICAgICAgNTUsXG4gICAgICAgIDk0LFxuICAgICAgICAxMDgsXG4gICAgICAgIDkzLFxuICAgICAgICAxOTksXG4gICAgICAgIDI0OSxcbiAgICAgICAgNDMsXG4gICAgICAgIDEzMSxcbiAgICAgICAgMjA5LFxuICAgICAgICAyOSxcbiAgICAgICAgOCxcbiAgICAgICAgMTY5LFxuICAgICAgICAxNDAsXG4gICAgICAgIDgyLFxuICAgICAgICAyMDIsXG4gICAgICAgIDE3OCxcbiAgICAgICAgMjA4LFxuICAgICAgICA3NSxcbiAgICAgICAgMTc2LFxuICAgICAgICAyMjksXG4gICAgICAgIDIzNyxcbiAgICAgICAgMTM2LFxuICAgICAgICA2MixcbiAgICAgICAgMTk4LFxuICAgICAgICA0NSxcbiAgICAgICAgMzYsXG4gICAgICAgIDQwXG4gICAgICBdXG4gICAgfVxuICB9LFxuICBcInBhaXJpbmdFcGhlbWVyYWxLZXlQYWlyXCI6IHtcbiAgICBcInByaXZhdGVcIjoge1xuICAgICAgXCJ0eXBlXCI6IFwiQnVmZmVyXCIsXG4gICAgICBcImRhdGFcIjogW1xuICAgICAgICAxOTIsXG4gICAgICAgIDI0LFxuICAgICAgICAyMzUsXG4gICAgICAgIDU3LFxuICAgICAgICAyMixcbiAgICAgICAgMjQ2LFxuICAgICAgICA2NyxcbiAgICAgICAgMzUsXG4gICAgICAgIDE0MixcbiAgICAgICAgMjQyLFxuICAgICAgICA4MCxcbiAgICAgICAgMTMsXG4gICAgICAgIDExMyxcbiAgICAgICAgMjQ2LFxuICAgICAgICA0NixcbiAgICAgICAgMTg3LFxuICAgICAgICA0OCxcbiAgICAgICAgNyxcbiAgICAgICAgMTI5LFxuICAgICAgICAxNDMsXG4gICAgICAgIDUsXG4gICAgICAgIDE4OCxcbiAgICAgICAgMTgyLFxuICAgICAgICAxMDIsXG4gICAgICAgIDIyNSxcbiAgICAgICAgMTc5LFxuICAgICAgICAxOTAsXG4gICAgICAgIDE3OCxcbiAgICAgICAgMTk0LFxuICAgICAgICAxMzQsXG4gICAgICAgIDE4OSxcbiAgICAgICAgMTE4XG4gICAgICBdXG4gICAgfSxcbiAgICBcInB1YmxpY1wiOiB7XG4gICAgICBcInR5cGVcIjogXCJCdWZmZXJcIixcbiAgICAgIFwiZGF0YVwiOiBbXG4gICAgICAgIDExNCxcbiAgICAgICAgMTU4LFxuICAgICAgICAyMzAsXG4gICAgICAgIDY4LFxuICAgICAgICA4NyxcbiAgICAgICAgMjE3LFxuICAgICAgICA3MyxcbiAgICAgICAgMTQ3LFxuICAgICAgICA3NSxcbiAgICAgICAgNTksXG4gICAgICAgIDE5OCxcbiAgICAgICAgODYsXG4gICAgICAgIDIxMSxcbiAgICAgICAgNSxcbiAgICAgICAgMTMzLFxuICAgICAgICA5OSxcbiAgICAgICAgMTk0LFxuICAgICAgICAxNTAsXG4gICAgICAgIDIxNixcbiAgICAgICAgMTgzLFxuICAgICAgICAxNjcsXG4gICAgICAgIDkxLFxuICAgICAgICAxNTAsXG4gICAgICAgIDU5LFxuICAgICAgICAyMTAsXG4gICAgICAgIDE5MixcbiAgICAgICAgMTgxLFxuICAgICAgICAxOTMsXG4gICAgICAgIDIwOCxcbiAgICAgICAgOTMsXG4gICAgICAgIDIxNixcbiAgICAgICAgODVcbiAgICAgIF1cbiAgICB9XG4gIH0sXG4gIFwic2lnbmVkSWRlbnRpdHlLZXlcIjoge1xuICAgIFwicHJpdmF0ZVwiOiB7XG4gICAgICBcInR5cGVcIjogXCJCdWZmZXJcIixcbiAgICAgIFwiZGF0YVwiOiBbXG4gICAgICAgIDE0NCxcbiAgICAgICAgNjksXG4gICAgICAgIDE4OSxcbiAgICAgICAgMTY3LFxuICAgICAgICAyMTQsXG4gICAgICAgIDEzOCxcbiAgICAgICAgMTEsXG4gICAgICAgIDE5NCxcbiAgICAgICAgMTEzLFxuICAgICAgICAxNDEsXG4gICAgICAgIDI0NyxcbiAgICAgICAgMjE3LFxuICAgICAgICAxNjIsXG4gICAgICAgIDIzMCxcbiAgICAgICAgMTUzLFxuICAgICAgICA2LFxuICAgICAgICAzNCxcbiAgICAgICAgMjI4LFxuICAgICAgICAyMzEsXG4gICAgICAgIDE1NixcbiAgICAgICAgMzgsXG4gICAgICAgIDEyOCxcbiAgICAgICAgMTk3LFxuICAgICAgICA4OCxcbiAgICAgICAgOSxcbiAgICAgICAgMTMyLFxuICAgICAgICA1NixcbiAgICAgICAgMjA3LFxuICAgICAgICAxMTcsXG4gICAgICAgIDIyMyxcbiAgICAgICAgMTU1LFxuICAgICAgICA3N1xuICAgICAgXVxuICAgIH0sXG4gICAgXCJwdWJsaWNcIjoge1xuICAgICAgXCJ0eXBlXCI6IFwiQnVmZmVyXCIsXG4gICAgICBcImRhdGFcIjogW1xuICAgICAgICAxMDYsXG4gICAgICAgIDI0NyxcbiAgICAgICAgNzIsXG4gICAgICAgIDEyOSxcbiAgICAgICAgMjM0LFxuICAgICAgICAxNCxcbiAgICAgICAgMTU2LFxuICAgICAgICAyNDYsXG4gICAgICAgIDI0NCxcbiAgICAgICAgMTE3LFxuICAgICAgICAxOTcsXG4gICAgICAgIDM2LFxuICAgICAgICAzMCxcbiAgICAgICAgOTksXG4gICAgICAgIDcwLFxuICAgICAgICAxNDYsXG4gICAgICAgIDE3NixcbiAgICAgICAgMjMzLFxuICAgICAgICA3NSxcbiAgICAgICAgNDEsXG4gICAgICAgIDE1MixcbiAgICAgICAgMjYsXG4gICAgICAgIDEwNixcbiAgICAgICAgMTQzLFxuICAgICAgICA2NSxcbiAgICAgICAgMjMzLFxuICAgICAgICAxNDksXG4gICAgICAgIDIyLFxuICAgICAgICA5MixcbiAgICAgICAgMjI1LFxuICAgICAgICAyMzksXG4gICAgICAgIDk3XG4gICAgICBdXG4gICAgfVxuICB9LFxuICBcInNpZ25lZFByZUtleVwiOiB7XG4gICAgXCJrZXlQYWlyXCI6IHtcbiAgICAgIFwicHJpdmF0ZVwiOiB7XG4gICAgICAgIFwidHlwZVwiOiBcIkJ1ZmZlclwiLFxuICAgICAgICBcImRhdGFcIjogW1xuICAgICAgICAgIDEyOCxcbiAgICAgICAgICA1NixcbiAgICAgICAgICAyNDMsXG4gICAgICAgICAgMTY3LFxuICAgICAgICAgIDIyNSxcbiAgICAgICAgICAxOTYsXG4gICAgICAgICAgMTgyLFxuICAgICAgICAgIDE4MCxcbiAgICAgICAgICAxNDAsXG4gICAgICAgICAgMTg5LFxuICAgICAgICAgIDE4MCxcbiAgICAgICAgICAyMDAsXG4gICAgICAgICAgMjQyLFxuICAgICAgICAgIDI0LFxuICAgICAgICAgIDI3LFxuICAgICAgICAgIDU5LFxuICAgICAgICAgIDE3OCxcbiAgICAgICAgICA4MyxcbiAgICAgICAgICA1NCxcbiAgICAgICAgICAxODUsXG4gICAgICAgICAgMTg0LFxuICAgICAgICAgIDQxLFxuICAgICAgICAgIDEzOSxcbiAgICAgICAgICA5MixcbiAgICAgICAgICAxMDUsXG4gICAgICAgICAgMTgyLFxuICAgICAgICAgIDYzLFxuICAgICAgICAgIDIwOSxcbiAgICAgICAgICA1NSxcbiAgICAgICAgICAxNDEsXG4gICAgICAgICAgMTM0LFxuICAgICAgICAgIDczXG4gICAgICAgIF1cbiAgICAgIH0sXG4gICAgICBcInB1YmxpY1wiOiB7XG4gICAgICAgIFwidHlwZVwiOiBcIkJ1ZmZlclwiLFxuICAgICAgICBcImRhdGFcIjogW1xuICAgICAgICAgIDM3LFxuICAgICAgICAgIDUsXG4gICAgICAgICAgMTIyLFxuICAgICAgICAgIDE0MixcbiAgICAgICAgICA3OCxcbiAgICAgICAgICAxODQsXG4gICAgICAgICAgMjQ0LFxuICAgICAgICAgIDM4LFxuICAgICAgICAgIDIwMCxcbiAgICAgICAgICAyNixcbiAgICAgICAgICAxODcsXG4gICAgICAgICAgMTMyLFxuICAgICAgICAgIDE2MixcbiAgICAgICAgICAxMzAsXG4gICAgICAgICAgMjMyLFxuICAgICAgICAgIDI0NixcbiAgICAgICAgICAxOSxcbiAgICAgICAgICAzNCxcbiAgICAgICAgICAyMTMsXG4gICAgICAgICAgNjIsXG4gICAgICAgICAgMTA3LFxuICAgICAgICAgIDQ1LFxuICAgICAgICAgIDIwNixcbiAgICAgICAgICA5NyxcbiAgICAgICAgICAyNDIsXG4gICAgICAgICAgMzUsXG4gICAgICAgICAgMTAyLFxuICAgICAgICAgIDEzLFxuICAgICAgICAgIDE2NCxcbiAgICAgICAgICAyNyxcbiAgICAgICAgICA5OCxcbiAgICAgICAgICAzMlxuICAgICAgICBdXG4gICAgICB9XG4gICAgfSxcbiAgICBcInNpZ25hdHVyZVwiOiB7XG4gICAgICBcInR5cGVcIjogXCJCdWZmZXJcIixcbiAgICAgIFwiZGF0YVwiOiBbXG4gICAgICAgIDEzNixcbiAgICAgICAgMjQxLFxuICAgICAgICAxNTIsXG4gICAgICAgIDE5LFxuICAgICAgICAxOTYsXG4gICAgICAgIDY4LFxuICAgICAgICAxODEsXG4gICAgICAgIDIsXG4gICAgICAgIDE5MyxcbiAgICAgICAgNjUsXG4gICAgICAgIDQ2LFxuICAgICAgICAyMixcbiAgICAgICAgMTI0LFxuICAgICAgICAyNTQsXG4gICAgICAgIDY1LFxuICAgICAgICA1OSxcbiAgICAgICAgNjIsXG4gICAgICAgIDE2MCxcbiAgICAgICAgMjEyLFxuICAgICAgICAxNjIsXG4gICAgICAgIDI0NyxcbiAgICAgICAgMjQsXG4gICAgICAgIDg4LFxuICAgICAgICAxNDQsXG4gICAgICAgIDE3MixcbiAgICAgICAgMTY1LFxuICAgICAgICAyMCxcbiAgICAgICAgMTEwLFxuICAgICAgICAxNDUsXG4gICAgICAgIDk4LFxuICAgICAgICA4NyxcbiAgICAgICAgMTg0LFxuICAgICAgICAyMDUsXG4gICAgICAgIDE5OCxcbiAgICAgICAgODEsXG4gICAgICAgIDIwNCxcbiAgICAgICAgOTcsXG4gICAgICAgIDE1NSxcbiAgICAgICAgMjQxLFxuICAgICAgICAxMzAsXG4gICAgICAgIDUxLFxuICAgICAgICAxMixcbiAgICAgICAgMTAwLFxuICAgICAgICA0MixcbiAgICAgICAgNDMsXG4gICAgICAgIDI2LFxuICAgICAgICAyNTUsXG4gICAgICAgIDIwMCxcbiAgICAgICAgOTgsXG4gICAgICAgIDEzOSxcbiAgICAgICAgMTY0LFxuICAgICAgICAyMjYsXG4gICAgICAgIDQ5LFxuICAgICAgICAyNDIsXG4gICAgICAgIDIxMSxcbiAgICAgICAgODIsXG4gICAgICAgIDI1NCxcbiAgICAgICAgMTU0LFxuICAgICAgICA3OSxcbiAgICAgICAgNDUsXG4gICAgICAgIDgyLFxuICAgICAgICA4MixcbiAgICAgICAgMjM5LFxuICAgICAgICAxMzNcbiAgICAgIF1cbiAgICB9LFxuICAgIFwia2V5SWRcIjogMVxuICB9LFxuICBcInJlZ2lzdHJhdGlvbklkXCI6IDYxLFxuICBcImFkdlNlY3JldEtleVwiOiBcIndOWW9WYlg0KzFFQWJHb2xtc01TMXVDZFh6QXYwMVhSbGFiNk9pRm9HRDg9XCIsXG4gIFwicHJvY2Vzc2VkSGlzdG9yeU1lc3NhZ2VzXCI6IFtcbiAgICB7XG4gICAgICBcImtleVwiOiB7XG4gICAgICAgIFwicmVtb3RlSmlkXCI6IFwiMjM0OTA2NzA4MjY5OUBzLndoYXRzYXBwLm5ldFwiLFxuICAgICAgICBcImZyb21NZVwiOiB0cnVlLFxuICAgICAgICBcImlkXCI6IFwiNUIxMDRBMzdCREU0MUY5MUQwOTI3MUYwQzVENTA3OEVcIlxuICAgICAgfSxcbiAgICAgIFwibWVzc2FnZVRpbWVzdGFtcFwiOiAxNzI1Mjg0NzYyXG4gICAgfVxuICBdLFxuICBcIm5leHRQcmVLZXlJZFwiOiAzMSxcbiAgXCJmaXJzdFVudXBsb2FkZWRQcmVLZXlJZFwiOiAzMSxcbiAgXCJhY2NvdW50U3luY0NvdW50ZXJcIjogMCxcbiAgXCJhY2NvdW50U2V0dGluZ3NcIjoge1xuICAgIFwidW5hcmNoaXZlQ2hhdHNcIjogZmFsc2VcbiAgfSxcbiAgXCJkZXZpY2VJZFwiOiBcIlpkMjlBeEdaU1NleHRKOHJjRHc4M0FcIixcbiAgXCJwaG9uZUlkXCI6IFwiYzM2YjQ1NDUtZTFmNC00OTNlLTgxYjItZmJmZjJmMzk1MzdhXCIsXG4gIFwiaWRlbnRpdHlJZFwiOiB7XG4gICAgXCJ0eXBlXCI6IFwiQnVmZmVyXCIsXG4gICAgXCJkYXRhXCI6IFtcbiAgICAgIDE2NyxcbiAgICAgIDIzNSxcbiAgICAgIDI3LFxuICAgICAgMjM4LFxuICAgICAgMTkxLFxuICAgICAgMSxcbiAgICAgIDE5NixcbiAgICAgIDUxLFxuICAgICAgMTgsXG4gICAgICAxMDMsXG4gICAgICAxMzAsXG4gICAgICAxMDYsXG4gICAgICAyMjksXG4gICAgICA0MSxcbiAgICAgIDcxLFxuICAgICAgMTI5LFxuICAgICAgMTMsXG4gICAgICAzNyxcbiAgICAgIDE2MyxcbiAgICAgIDE3MFxuICAgIF1cbiAgfSxcbiAgXCJyZWdpc3RlcmVkXCI6IHRydWUsXG4gIFwiYmFja3VwVG9rZW5cIjoge1xuICAgIFwidHlwZVwiOiBcIkJ1ZmZlclwiLFxuICAgIFwiZGF0YVwiOiBbXG4gICAgICA5OSxcbiAgICAgIDg0LFxuICAgICAgMTc3LFxuICAgICAgMCxcbiAgICAgIDQ3LFxuICAgICAgMTMsXG4gICAgICA2NyxcbiAgICAgIDE3OSxcbiAgICAgIDE2OCxcbiAgICAgIDkxLFxuICAgICAgMjksXG4gICAgICAxOTksXG4gICAgICAyNTQsXG4gICAgICA2OCxcbiAgICAgIDE5MyxcbiAgICAgIDYsXG4gICAgICA3NixcbiAgICAgIDE4OCxcbiAgICAgIDIwMCxcbiAgICAgIDIzOVxuICAgIF1cbiAgfSxcbiAgXCJyZWdpc3RyYXRpb25cIjoge30sXG4gIFwicGFpcmluZ0NvZGVcIjogXCI5NUdDNFdXQ1wiLFxuICBcIm1lXCI6IHtcbiAgICBcImlkXCI6IFwiMjM0OTA2NzA4MjY5OTozQHMud2hhdHNhcHAubmV0XCIsXG4gICAgXCJuYW1lXCI6IFwiVG9tbXkgQ29uY2VwdFwiLFxuICAgIFwibGlkXCI6IFwiNTU2NjI5NjA3MTM3NjU6M0BsaWRcIlxuICB9LFxuICBcImFjY291bnRcIjoge1xuICAgIFwiZGV0YWlsc1wiOiBcIkNQU3dwN0VGRUkrRDE3WUdHQUVnQUNnQVwiLFxuICAgIFwiYWNjb3VudFNpZ25hdHVyZUtleVwiOiBcIkU2YTJteTRVMjhlNTRjTnExY2t4QU9JWkpTUmtheFBaMzl4VDdGNSthaFk9XCIsXG4gICAgXCJhY2NvdW50U2lnbmF0dXJlXCI6IFwiMmNncXpwRUNGTjdKQ2JOMGhwOEQ3NTg5blBCZm9IbXVGVEhUSFhFSVVHcGh1ajdQNHVyS1U2Z2p1emcwRkFvbEhhUndnMEFUVDZpVE9ZME53VEJPRHc9PVwiLFxuICAgIFwiZGV2aWNlU2lnbmF0dXJlXCI6IFwieTg4VThPTjlGSGtyM3lUWFU2N055aTJYcUhWZ0I2aXZOdmdLNCtSNFFBVDlSMnRjTFFZTlFLS05SV1VNZUx6VzE2UExHa0FJWEsrMklNT0NFUzVSaFE9PVwiXG4gIH0sXG4gIFwic2lnbmFsSWRlbnRpdGllc1wiOiBbXG4gICAge1xuICAgICAgXCJpZGVudGlmaWVyXCI6IHtcbiAgICAgICAgXCJuYW1lXCI6IFwiMjM0OTA2NzA4MjY5OTozQHMud2hhdHNhcHAubmV0XCIsXG4gICAgICAgIFwiZGV2aWNlSWRcIjogMFxuICAgICAgfSxcbiAgICAgIFwiaWRlbnRpZmllcktleVwiOiB7XG4gICAgICAgIFwidHlwZVwiOiBcIkJ1ZmZlclwiLFxuICAgICAgICBcImRhdGFcIjogW1xuICAgICAgICAgIDUsXG4gICAgICAgICAgMTksXG4gICAgICAgICAgMTY2LFxuICAgICAgICAgIDE4MixcbiAgICAgICAgICAxNTUsXG4gICAgICAgICAgNDYsXG4gICAgICAgICAgMjAsXG4gICAgICAgICAgMjE5LFxuICAgICAgICAgIDE5OSxcbiAgICAgICAgICAxODUsXG4gICAgICAgICAgMjI1LFxuICAgICAgICAgIDE5NSxcbiAgICAgICAgICAxMDYsXG4gICAgICAgICAgMjEzLFxuICAgICAgICAgIDIwMSxcbiAgICAgICAgICA0OSxcbiAgICAgICAgICAwLFxuICAgICAgICAgIDIyNixcbiAgICAgICAgICAyNSxcbiAgICAgICAgICAzNyxcbiAgICAgICAgICAzNixcbiAgICAgICAgICAxMDAsXG4gICAgICAgICAgMTA3LFxuICAgICAgICAgIDE5LFxuICAgICAgICAgIDIxNyxcbiAgICAgICAgICAyMjMsXG4gICAgICAgICAgMjIwLFxuICAgICAgICAgIDgzLFxuICAgICAgICAgIDIzNixcbiAgICAgICAgICA5NCxcbiAgICAgICAgICAxMjYsXG4gICAgICAgICAgMTA2LFxuICAgICAgICAgIDIyXG4gICAgICAgIF1cbiAgICAgIH1cbiAgICB9XG4gIF0sXG4gIFwicGxhdGZvcm1cIjogXCJzbWJhXCIsXG4gIFwibGFzdEFjY291bnRTeW5jVGltZXN0YW1wXCI6IDE3MjUyODQ3NTUsXG4gIFwibXlBcHBTdGF0ZUtleUlkXCI6IFwiQUFBQUFBeTRcIlxufSIsCiAgImFwcC1zdGF0ZS1zeW5jLWtleS1BQUFBQUF5NC5qc29uIjogIntcImtleURhdGFcIjpcIjR5WXlTNEd2V2c2MkRYQnVxMmRKeDNJek1vZktQcFRCaFEvaXc3cncrL2M9XCIsXCJmaW5nZXJwcmludFwiOntcInJhd0lkXCI6MTQ0NTU4Mjk2MyxcImN1cnJlbnRJbmRleFwiOjEsXCJkZXZpY2VJbmRleGVzXCI6WzAsMV19LFwidGltZXN0YW1wXCI6XCIxNzIyMTg1OTkwMDY1XCJ9Igp9",  // PUT SESSION ID HERE 
  errorChat : process.env.ERROR_CHAT || "",
  KOYEB_API : process.env.KOYEB_API  || "false",

  REMOVE_BG_KEY : process.env.REMOVE_BG_KEY  || "",
  OPENAI_API_KEY: process.env.OPENAI_API_KEY || "",
  HEROKU_API_KEY: process.env.HEROKU_API_KEY || "",
  HEROKU_APP_NAME:process.env.HEROKU_APP_NAME|| "",
  antilink_values:process.env.ANTILINK_VALUES|| "all",
  HEROKU: process.env.HEROKU_APP_NAME && process.env.HEROKU_API_KEY,

  aitts_Voice_Id : process.env.AITTS_ID || "37",
  ELEVENLAB_API_KEY: process.env.ELEVENLAB_API_KEY || "",
  WORKTYPE: process.env.WORKTYPE||process.env.MODE || "private",
  LANG: process.env.THEME ? process.env.THEME.toUpperCase() : "SUHAIL",



};




























global.isMongodb = false; 
let file = require.resolve(__filename)
fs.watchFile(file, () => { fs.unwatchFile(file);console.log(`Update'${__filename}'`);delete require.cache[file];	require(file); })
 

// ========================= [ Disables in V.1.2.8 ] ===============================\\  
  //style : process.env.STYLE || "2",  // put '1' & "2" here to check bot styles
  //readmessage:process.env.READ_MESSAGE|| "false",
  //warncount: process.env.WARN_COUNT || 3,
  //userImages:process.env.USER_IMAGES|| "text",  // SET IMAGE AND VIDEO URL FOR BOT MENUS 
  //disablepm: process.env.DISABLE_PM || "false",
  //MsgsInLog: process.env.MSGS_IN_LOG|| "false", // "true"  to see messages , "log" to open logs , "false" to hide logs messages
  //readcmds:process.env.READ_COMMANDS|| "false", 
  //alwaysonline:process.env.WAPRESENCE|| "unavailable", // 'unavailable' | 'online' | 'composing' | 'recording' | 'paused'
  //read_status: process.env.AUTO_READ_STATUS || "false",
  //save_status: process.env.AUTO_SAVE_STATUS || "false",
 
